// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RunScan(arg1:context.Context,arg2:string):Promise<string>;
