// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunScan(arg1) {
  return window['go']['backend']['Scanner']['RunScan'](arg1);
}
